port: 7890
socks-port: 7891
redir-port: 0
allow-lan: false
mode: Rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: ''


proxies:
- { name: "u9un-v2-HK-HongKong1",type: vmess,server: hk1.v2u9.top,port: 14444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-HK-HongKong2",type: vmess,server: hk2.v2u9.top,port: 14444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-HK-HongKong3",type: vmess,server: hk3.v2u9.top,port: 14444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-HK-HongKong4",type: vmess,server: hk4.v2u9.top,port: 14444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-HK-HongKong5",type: vmess,server: hk5.v2u9.top,port: 14444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-HK-HongKong6",type: vmess,server: hk6.v2u9.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-HK-HongKong7",type: vmess,server: hk7.v2u9.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-HK-HongKong8",type: vmess,server: hk8.v2u9.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-HK-HongKong9",type: vmess,server: hk9.v2u9.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-HK-HongKong0",type: vmess,server: hk0.v2u9.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-JP-Tokyo1",type: vmess,server: jp1.v2u9.top,port: 31444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-JP-Tokyo2",type: vmess,server: jp2.v2u9.top,port: 31444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-JP-Tokyo3",type: vmess,server: jp3.v2u9.top,port: 31444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-JP-Tokyo4",type: vmess,server: jp4.v2u9.top,port: 31444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-JP-Tokyo5",type: vmess,server: jp5.v2u9.top,port: 31444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-JP-Tokyo6",type: vmess,server: jp6.v2u9.top,port: 31444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-JP-Tokyo7",type: vmess,server: jp7.v2u9.top,port: 31444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-JP-Tokyo8",type: vmess,server: jp8.v2u9.top,port: 31444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-TW-Taipei1",type: vmess,server: tw1.v2u9.top,port: 34444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-TW-Taipei2",type: vmess,server: tw2.v2u9.top,port: 34444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-TW-Taipei3",type: vmess,server: tw3.v2u9.top,port: 34444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-TW-Taipei4",type: vmess,server: tw4.v2u9.top,port: 34444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-SG-Singapore1",type: vmess,server: sg1.v2u9.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 1,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-SG-Singapore2",type: vmess,server: sg2.u9v2.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 1,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-SG-Singapore3",type: vmess,server: sg3.u9v2.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 1,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-SG-Singapore4",type: vmess,server: sg4.u9v2.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 1,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-SG-Singapore5",type: vmess,server: sg5.u9v2.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 1,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-SG-Singapore6",type: vmess,server: sg6.u9v2v2.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 1,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-SG-Singapore7",type: vmess,server: sg7.u9v2v2.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 1,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-SG-Singapore8",type: vmess,server: sg8.u9v2v2.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 1,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-SG-Singapore9",type: vmess,server: sg9.u9v2v2.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 1,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-SG-Singapore0",type: vmess,server: sg0.u9v2v2.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 1,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-KR-Seoul1",type: vmess,server: kr1.v2u9.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-KR-Seoul2",type: vmess,server: kr2.u9v2.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-KR-Seoul3",type: vmess,server: kr3.u9v2.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-KR-Seoul4",type: vmess,server: kr4.u9v2.top,port: 444,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-US-LosAngeles1",type: vmess,server: us1.u9v2v2.top,port: 443,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-US-LosAngeles2",type: vmess,server: us2.u9v2v2.top,port: 443,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-US-LosAngeles3",type: vmess,server: us3.u9v2v2.top,port: 443,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-US-LosAngeles4",type: vmess,server: us4.u9v2v2.top,port: 443,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-US-LosAngeles5",type: vmess,server: us5.u9v2v2.top,port: 443,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-US-LosAngeles6",type: vmess,server: us6.u9v2v2.top,port: 443,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-US-LosAngeles7",type: vmess,server: us7.u9v2v2.top,port: 443,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-US-LosAngeles8",type: vmess,server: us8.u9v2v2.top,port: 443,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-US-LosAngeles9",type: vmess,server: us9.u9v2v2.top,port: 443,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}
- { name: "u9un-v2-US-LosAngeles0",type: vmess,server: us0.u9v2v2.top,port: 443,uuid: CE21AA9B-2740-6A0E-D82E-22E5D55ECB83,alterId: 0,cipher: none, network: ws, tls: true}


proxy-groups:

  - name: "40型号V2云服务器一年"
    type: select
    proxies: ["u9un-v2-HK-HongKong1", "u9un-v2-HK-HongKong2", "u9un-v2-HK-HongKong3", "u9un-v2-HK-HongKong4", "u9un-v2-HK-HongKong5", "u9un-v2-HK-HongKong6", "u9un-v2-HK-HongKong7", "u9un-v2-HK-HongKong8", "u9un-v2-HK-HongKong9", "u9un-v2-HK-HongKong0", "u9un-v2-JP-Tokyo1", "u9un-v2-JP-Tokyo2", "u9un-v2-JP-Tokyo3", "u9un-v2-JP-Tokyo4", "u9un-v2-JP-Tokyo5", "u9un-v2-JP-Tokyo6", "u9un-v2-JP-Tokyo7", "u9un-v2-JP-Tokyo8", "u9un-v2-TW-Taipei1", "u9un-v2-TW-Taipei2", "u9un-v2-TW-Taipei3", "u9un-v2-TW-Taipei4", "u9un-v2-SG-Singapore1", "u9un-v2-SG-Singapore2", "u9un-v2-SG-Singapore3", "u9un-v2-SG-Singapore4", "u9un-v2-SG-Singapore5", "u9un-v2-SG-Singapore6", "u9un-v2-SG-Singapore7", "u9un-v2-SG-Singapore8", "u9un-v2-SG-Singapore9", "u9un-v2-SG-Singapore0", "u9un-v2-KR-Seoul1", "u9un-v2-KR-Seoul2", "u9un-v2-KR-Seoul3", "u9un-v2-KR-Seoul4", "u9un-v2-US-LosAngeles1", "u9un-v2-US-LosAngeles2", "u9un-v2-US-LosAngeles3", "u9un-v2-US-LosAngeles4", "u9un-v2-US-LosAngeles5", "u9un-v2-US-LosAngeles6", "u9un-v2-US-LosAngeles7", "u9un-v2-US-LosAngeles8", "u9un-v2-US-LosAngeles9", "u9un-v2-US-LosAngeles0"]

  - name: "⛽ 剩余流量(非实时, 刷新订阅更新):35070MB"
    type: select
    proxies:
      - DIRECT

  - name: "📅 到期时间:2023-04-08"
    type: select
    proxies:
      - DIRECT

rules:
- DOMAIN-SUFFIX,google.com,40型号V2云服务器一年
- DOMAIN-KEYWORD,google,40型号V2云服务器一年
- DOMAIN-KEYWORD,linkedin,40型号V2云服务器一年
- DOMAIN,google.com,40型号V2云服务器一年

# LAN
- IP-CIDR,0.0.0.0/8,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- IP-CIDR,169.254.0.0/16,DIRECT
- IP-CIDR,192.0.0.0/24,DIRECT
- IP-CIDR,192.0.2.0/24,DIRECT
- IP-CIDR,192.88.99.0/24,DIRECT
- IP-CIDR,198.18.0.0/15,DIRECT
- IP-CIDR,198.51.100.0/24,DIRECT
- IP-CIDR,203.0.113.0/24,DIRECT
- IP-CIDR,224.0.0.0/4,DIRECT
- IP-CIDR,240.0.0.0/4,DIRECT
- IP-CIDR,255.255.255.255/32,DIRECT

- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT

- GEOIP,CN,DIRECT
- MATCH,40型号V2云服务器一年
